# 2020-02-08 {#feb08}

**General:**  
Team met to discuss next steps on splitting up documentation. Was decided to split as follows:

- Nate: Populate metadata files and start looking into ensuring that all files meet CRAN requirements.
- Mitch: Populate all roxygen documentation.
- Ryan: Create vignette and README

**Nate Completed:**  

- Created a new branch `update_CICD_workflow` and PR/merged in new workflow files to reduce the number of CICD actions performed https://github.com/WraySmith/caRecall/pull/32:
    - Action workflow to run R-CMD-Check on 4 different OS but is only triggered by a using through the Github Action UI
    - Action workflow to run R-CMD-Check on both push and pull but only on MacOS and which also runs the coverage test
- Created a new branch `populate-metadata` and PR/merged in https://github.com/WraySmith/caRecall/pull/33. Includes:
    - updated DESCRIPTION file
    - minor updates on multiple metadata files
    - added NEWS.md and cran-comments.md
    - also added ability for user to pass in an API key directly to a function



